USE [master]
GO
/****** Object:  Database [FormViewAccess]    Script Date: 27/04/2017 4:33:40 p. m. ******/
CREATE DATABASE [FormViewAccess] ON  PRIMARY 
( NAME = N'FormViewAccess', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS2008R2\MSSQL\DATA\FormViewAccess.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FormViewAccess_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS2008R2\MSSQL\DATA\FormViewAccess_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FormViewAccess] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FormViewAccess].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FormViewAccess] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FormViewAccess] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FormViewAccess] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FormViewAccess] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FormViewAccess] SET ARITHABORT OFF 
GO
ALTER DATABASE [FormViewAccess] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FormViewAccess] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FormViewAccess] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FormViewAccess] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FormViewAccess] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FormViewAccess] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FormViewAccess] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FormViewAccess] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FormViewAccess] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FormViewAccess] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FormViewAccess] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FormViewAccess] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FormViewAccess] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FormViewAccess] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FormViewAccess] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FormViewAccess] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FormViewAccess] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FormViewAccess] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FormViewAccess] SET  MULTI_USER 
GO
ALTER DATABASE [FormViewAccess] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FormViewAccess] SET DB_CHAINING OFF 
GO
USE [FormViewAccess]
GO
/****** Object:  Table [dbo].[VBO_Profile]    Script Date: 27/04/2017 4:33:40 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VBO_Profile](
	[ProfileID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Website] [nvarchar](150) NOT NULL,
	[Youtube] [nvarchar](150) NOT NULL,
	[Facebook] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_VBO_Profile] PRIMARY KEY CLUSTERED 
(
	[ProfileID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [FormViewAccess] SET  READ_WRITE 
GO
